# Generated by Django 5.1 on 2024-08-19 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaNegocio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=20)),
                ("descripcion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Negocio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=40)),
                ("razon_social", models.CharField(max_length=40)),
                ("direccion", models.CharField(max_length=40)),
                ("nit", models.IntegerField()),
                ("correo", models.EmailField(max_length=254)),
                (
                    "area_negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="negocios.areanegocio",
                    ),
                ),
            ],
        ),
    ]
